plugins {
    id 'java-library'
    id 'dependency-management'

    id 'com.palantir.baseline-idea'
    // 代码静态检查插件
    id 'com.palantir.baseline-error-prone'

    // 引入nullaway进行Jspecity分析检查（这里采用了baseline提出的封装引入，避免手动引入uber.nullaway导致的兼容问题）
    id 'com.palantir.baseline-null-away'

    // 代码格式检查插件
    id 'com.palantir.baseline-checkstyle'

    // 代码自动格式化插件
    id 'com.diffplug.spotless'
    id 'com.palantir.java-format' // palantir风格

    id 'com.palantir.baseline-encoding'
    id 'com.palantir.baseline-exact-dependencies' // 帮助优化依赖关系
}

description = "palantir baseline代码规范化插件"

dependencies {
    // JSpecify: null检查
    implementation "org.jspecify:jspecify"
}

// 代码自动格式化配置.
spotless {
    java {
        target 'src/main/java/**/*.java', 'src/main/test/**/*.java'
        lineEndings com.diffplug.spotless.LineEnding.UNIX
        endWithNewline()
        leadingTabsToSpaces 4
        trimTrailingWhitespace()
        custom 'Lambda fix', { it.replace('} )', '})').replace('} ,', '},') }
    }
    groovyGradle {
        greclipse()
    }
}

compileJava {
    options.errorprone.disable 'AssignmentExpression',
            // 禁止palantir的SafeLogging
            'Slf4jLogsafeArgs',
            // 禁止Safe系列异常
            'PreferSafeLoggableExceptions',
            // 禁止palantir的Preconditions
            'PreferSafeLoggingPreconditions',
            // 禁止palantir的严格未使用变量
            'StrictUnusedVariable'
    options.compilerArgs += ['-Werror', '-implicit:class']
}
