plugins {
	id 'io.spring.dependency-management'
}

// 仓库配置
repositories {
	maven {
		url = 'https://maven.cnb.cool/ziyframework/maven/-/packages/'
	}
	mavenCentral()
	mavenLocal()
}

dependencyManagement {
	imports {
		def springBootVersion = providers.gradleProperty('versions.spring-boot').getOrElse('4.0.6')
		mavenBom "org.springframework.boot:spring-boot-dependencies:${springBootVersion}"
		mavenBom "me.ziyframework:dependencies:0.1.6-SNAPSHOT"
	}
	dependencies {
		// jpa-modelgen版本
		def hibernateVersion = dependencyManagement.importedProperties.get('hibernate.version')
		dependency "org.hibernate:hibernate-jpamodelgen:${hibernateVersion}"

		// mapstruct
		dependency 'org.mapstruct:mapstruct:1.6.3'
		dependency 'org.mapstruct:mapstruct-processor:1.6.3'
		dependency 'org.mapstruct.extensions.spring:mapstruct-spring-annotations:2.0.0'
		dependency 'org.projectlombok:lombok-mapstruct-binding:0.2.0'

		dependency 'p6spy:p6spy:3.9.1'

		// manifold
		dependencySet(group: 'systems.manifold', version: '2026.1.4') {
			entry 'manifold-ext'
			entry 'manifold-ext-rt'
			entry 'manifold'
		}

		// blaze
		dependencySet(group: 'com.blazebit', version: '1.6.18') {
			entry 'blaze-persistence-core-api-jakarta'
			entry 'blaze-persistence-entity-view-api-jakarta'
			entry 'blaze-persistence-entity-view-impl-jakarta'
			entry 'blaze-persistence-entity-view-processor-jakarta'
			entry 'blaze-persistence-integration-spring-data-4.0'
			entry 'blaze-persistence-integration-hibernate-7.1'
		}

		// process
		dependency 'com.google.auto.service:auto-service:1.1.1'
	}
}

