plugins {
	id 'base'
	id 'java'
	id 'idea' // idea的gradle插件
	id 'dependency-management'
}

description = "Java开发基础包，引入该插件即可使用Java开发基础功能"

java {
	// 管理gradle构建过程中的JDK版本，推荐使用，避免因为Gradle构建中JDK版本不同导致的问题
	// 输出工具链信息: ./gradlew -q javaToolchains
	// 已关闭自动下载,见gradle.properties
	toolchain {
		languageVersion = JavaLanguageVersion.of(25)
	}
	sourceCompatibility = JavaLanguageVersion.of(25)
	targetCompatibility = JavaLanguageVersion.of(25)
}

tasks.withType(JavaCompile).configureEach {
	options.encoding = "UTF-8"
}


