# 配置gradlew的运行参数(运行行为)
# 关闭工具链自动下载JDK
org.gradle.java.installations.auto-download=false
# 打开守护进程, 服务器上自动构建需要关闭(gradlew --no-daemon)
org.gradle.daemon=true
# 开启并行编译
org.gradle.parallel=true
# 开启编译缓存
org.gradle.caching=true
# 解决java-format插件导致的模块化问题
org.gradle.jvmargs=--add-opens jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED \
  --add-opens jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED \
  --add-opens jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED \
  --add-opens jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED \
  --add-opens jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED \
  --add-opens jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED \
  --add-opens jdk.compiler/com.sun.tools.javac.comp=ALL-UNNAMED \
  --add-opens jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED \
  --add-opens jdk.compiler/com.sun.tools.javac.model=ALL-UNNAMED \
  --add-opens jdk.compiler/com.sun.tools.javac.processing=ALL-UNNAMED \
  -Xmx512m
# 允许格式化gradle文件
com.palantir.baseline-format.gradle-files=true

# groupId
groupId=me.ziyframework
# 版本管理
versions.jdk=25
versions.spring-boot=4.0.6
