plugins {
    id 'groovy-gradle-plugin'
}

dependencies {
    implementation gradleApi()
    implementation localGroovy()

    implementation 'io.spring.dependency-management:io.spring.dependency-management.gradle.plugin:1.1.7'
    implementation "org.springframework.boot:org.springframework.boot.gradle.plugin:4.0.6" // SpringBoot版本

    implementation "com.palantir.baseline:com.palantir.baseline.gradle.plugin:7.5.0"

    // palantir java-format
    implementation "com.palantir.java-format:com.palantir.java-format.gradle.plugin:2.91.0"
    implementation "com.diffplug.spotless:com.diffplug.spotless.gradle.plugin:8.5.1"
}

repositories {
    gradlePluginPortal()
    mavenCentral()
    maven { url = 'https://maven.aliyun.com/repository/public'}
    mavenLocal()
}

