plugins {
	id 'java-basic'
	id 'baseline'
	id 'spring-boot-support'
	id 'jpa'
}

description =  '数据持久化快速开发模块'

dependencies {
	implementation 'me.ziyframework.boot:core-spring-boot-starter'
	implementation 'org.springframework.boot:spring-boot-starter'
	api 'me.ziyframework:core'

	// process处理
	api 'me.ziyframework.process:apt-common'
	implementation 'com.palantir.javapoet:javapoet'
	implementation 'jakarta.persistence:jakarta.persistence-api'
	implementation 'com.google.auto.service:auto-service'
}

tasks.withType(JavaCompile).configureEach {
	options.compilerArgs += [
		"--add-exports",
		"jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED",
		"--add-exports",
		"jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED",
		"--add-exports",
		"jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED",
		"--add-exports",
		"jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED",
		"--add-exports",
		"jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED",
		"--add-exports",
		"jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED",
		"--add-exports",
		"jdk.compiler/com.sun.tools.javac.comp=ALL-UNNAMED",
		"--add-exports",
		"jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED",
		"--add-exports",
		"jdk.compiler/com.sun.tools.javac.model=ALL-UNNAMED",
		"--add-exports",
		"jdk.compiler/com.sun.tools.javac.processing=ALL-UNNAMED",
	]
}
