package me.ziyframework.buildsrc

import java.security.MessageDigest
import org.gradle.api.logging.Logger

class HookInstaller {
	static void sync(File hookFile, String command, Logger logger) {
		def header = "#!/usr/bin/env bash\n# Auto-generated by git-hooks gradle plugin. Do not edit.\nset -e\n"
		def target = header + command + '\n'

		if (hookFile.exists() && MessageDigest.isEqual(
				MessageDigest.getInstance('MD5').digest(hookFile.bytes),
				MessageDigest.getInstance('MD5').digest(target.bytes))) {
			return
		}

		hookFile.text = target
		hookFile.setExecutable(true, false)
		logger.lifecycle("已写入 pre-push hook: ${hookFile.absolutePath}")
	}
}